### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 111678900** [bowang-lab/MedSAMSlicer#14]
Traceback (most recent call last):
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/ASUS/Downloads/MedSAMSlicer-0.04 (1)/MedSAMSlicer-0.04/MedSAM/MedSAMLite/MedSAMLite.py", line 500, in pip_install_wrapper
    slicer.util.pip_install(command)
  File "D:\AndrowsData\app\Slicer 5.6.1\bin\Python\slicer\util.py", line 3887, in pip_install
    _executePythonModule("pip", args)
  File "D:\AndrowsData\app\Slicer 5.6.1\bin\Python\slicer\util.py", line 3848, in _executePythonModule
    logProcessOutput(proc)
  File "D:\AndrowsData\app\Slicer 5.6.1\bin\Python\slicer\util.py", line 3814, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['D:/AndrowsData/app/Slicer 5.6.1/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'torch==2.0.1', 'torchvision==0.15.2']' returned non-zero exit status 2.

**Comment by Tiam66** [comment]
I have the same problem,did you solve it?

**Comment by 111678900** [comment]
No😭



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 2, 2024 21:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bowang-lab/MedSAMSlicer] Hello (Issue #14)




 
I have the same problem,did you solve it?

**Comment by rasakereh** [comment]
Hi, sorry for the late reply. In the toolbar, the rightmost logo (blue and yellow) is the python console. Click on it and a textbox will show up with the title "Python Console". Please type the following in it and click enter and share the results:

`pip_install('torch==2.0.1')`
