### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 111678900** [bowang-lab/MedSAMSlicer#15]
ERROR: Exception:
Traceback (most recent call last):
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\http\client.py", line 463, in read
    n = self.readinto(b)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\http\client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_internal\operations\prepare.py", line 552, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_internal\operations\prepare.py", line 467, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_internal\network\download.py", line 183, in __call__
    for chunk in chunks:
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\AndrowsData\app\Slicer 5.6.1\lib\Python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by rasakereh** [comment]
Hi, it seems like a network connection issue to me, would you please try again and make sure that your connection settings incl. proxy, etc are all reliably set?
