### ISSUE TITLE
cannot install dependencies.

### ISSUE THREAD

**Issue by Ouyngh** [bowang-lab/MedSAMSlicer#19]
slicer 5.6.1 but cannot install dependencies.
these is the errors:
Installation will happen in F:/slicer5.6/dependencies
Exception in thread Thread-7:
Traceback (most recent call last):
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "F:/slicer5.6/MedSAMSlicer-0.05/MedSAMSlicer-0.05/MedSAM/MedSAMLite/MedSAMLite.py", line 518, in download_wrapper
    with urlopen(url) as r:
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\urllib\request.py", line 1350, in do_open
    r = h.getresponse()
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\http\client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
![Snipaste_2024-03-18_12-47-09](https://github.com/bowang-lab/MedSAMSlicer/assets/125938773/1ea14ae5-4253-4d5f-a665-592f6e1f3f5b)

**Comment by Ouyngh** [comment]
Python 3.9.10 (main, Dec 12 2023, 02:25:18) [MSC v.1935 64 bit (AMD64)] on win32
>>> 
Traceback (most recent call last):
  File "F:/slicer5.6/MedSAMSlicer-0.05/MedSAMSlicer-0.05/MedSAM/MedSAMLite/MedSAMLite.py", line 363, in enter
    self.initializeParameterNode()
  File "F:/slicer5.6/MedSAMSlicer-0.05/MedSAMSlicer-0.05/MedSAM/MedSAMLite/MedSAMLite.py", line 396, in initializeParameterNode
    self.setParameterNode(self.logic.getParameterNode())
  File "F:/slicer5.6/MedSAMSlicer-0.05/MedSAMSlicer-0.05/MedSAM/MedSAMLite/MedSAMLite.py", line 416, in setParameterNode
    self._parameterNodeGuiTag = self._parameterNode.connectGui(self.ui)
AttributeError: 'MedSAMLiteWidget' object has no attribute 'ui'
Installation will happen in F:/slicer5.6/dependencies
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/torch/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /simple/torch/
Could not fetch URL https://pypi.org/simple/torch/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/torch/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) - skipping
ERROR: Could not find a version that satisfies the requirement torch==2.0.1 (from versions: none)
ERROR: No matching distribution found for torch==2.0.1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "F:\slicer5.6\Slicer 5.6.1\lib\Python\Lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "F:/slicer5.6/MedSAMSlicer-0.05/MedSAMSlicer-0.05/MedSAM/MedSAMLite/MedSAMLite.py", line 513, in pip_install_wrapper
    slicer.util.pip_install(command)
  File "F:\slicer5.6\Slicer 5.6.1\bin\Python\slicer\util.py", line 3887, in pip_install
    _executePythonModule("pip", args)
  File "F:\slicer5.6\Slicer 5.6.1\bin\Python\slicer\util.py", line 3848, in _executePythonModule
    logProcessOutput(proc)
  File "F:\slicer5.6\Slicer 5.6.1\bin\Python\slicer\util.py", line 3814, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['F:/slicer5.6/Slicer 5.6.1/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'torch==2.0.1', 'torchvision==0.15.2']' returned non-zero exit status 1.
