### ISSUE TITLE
server_essentials ?

### ISSUE THREAD

**Issue by TheGodofthewilderness** [bowang-lab/MedSAMSlicer#20]
ERROR: D:\\ufffd\ufffd\ufffd\ufffd\MedSAMSlicer-0.04\MedSAMSlicer-0.04/server_essentials is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
Exception in thread Thread-12:
Traceback (most recent call last):
  File "D:\软件\Slicer 5.6.1\lib\Python\Lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "D:\软件\Slicer 5.6.1\lib\Python\Lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:/软件/MedSAMSlicer-0.04/MedSAMSlicer-0.04/MedSAM/MedSAMLite/MedSAMLite.py", line 501, in pip_install_wrapper
    slicer.util.pip_install(command)
  File "D:\软件\Slicer 5.6.1\bin\Python\slicer\util.py", line 3887, in pip_install
    _executePythonModule("pip", args)
  File "D:\软件\Slicer 5.6.1\bin\Python\slicer\util.py", line 3848, in _executePythonModule
    logProcessOutput(proc)
  File "D:\软件\Slicer 5.6.1\bin\Python\slicer\util.py", line 3814, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['D:/软件/Slicer 5.6.1/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', '-e', 'D:\\软件\\MedSAMSlicer-0.04\\MedSAMSlicer-0.04/server_essentials']' returned non-zero exit status 1.

**Comment by Guojfeng** [comment]
The installation path cannot contain Chinese characters "软件"

**Comment by rasakereh** [comment]
@TheGodofthewilderness  i believe @Guojfeng comment is a solution. did you try it out?
