### ISSUE TITLE
UnboundLocalError: local variable 'bbox_1024_center_inf' referenced before assignmen

### ISSUE THREAD

**Issue by cryudetao** [bowang-lab/MedSAMSlicer#30]
Traceback (most recent call last):
  File "E:/MedSAMSlicer-0.1/MedSAM/MedSAMLite/MedSAMLite.py", line 242, in <lambda>
    self.ui.pbSegment.connect('clicked(bool)', lambda: self.logic.applySegmentation())
  File "E:/MedSAMSlicer-0.1/MedSAM/MedSAMLite/MedSAMLite.py", line 727, in applySegmentation
    segmentation_mask = self.inferSegmentation()
  File "E:/MedSAMSlicer-0.1/MedSAM/MedSAMLite/MedSAMLite.py", line 681, in inferSegmentation
    seg_data = self.backend.infer(slice_idx, bbox, zrange)
  File "e:\medsamslicer-0.1\medsam\medsamlite\resources\server_essentials\medsam_interface\interface_impl.py", line 288, in infer
    bbox_1024_prev = bbox_1024_center_inf
UnboundLocalError: local variable 'bbox_1024_center_inf' referenced before assignmen

**Comment by rasakereh** [comment]
(The latest release)[https://github.com/bowang-lab/MedSAMSlicer/releases/tag/v0.11] has addressed this issue along with a handful of interesting new features. Try it out and lmk if error is still there
