### ISSUE TITLE
No ui

### ISSUE THREAD

**Issue by calm0602** [bowang-lab/MedSAMSlicer#37]
Traceback (most recent call last):
  File "C:/Users/26965/AppData/Local/slicer.org/Slicer 5.6.2/3d-slicer/MedSAMSlicer-0.1/MedSAM/MedSAMLite/MedSAMLite.py", line 366, in enter
    self.initializeParameterNode()
  File "C:/Users/26965/AppData/Local/slicer.org/Slicer 5.6.2/3d-slicer/MedSAMSlicer-0.1/MedSAM/MedSAMLite/MedSAMLite.py", line 399, in initializeParameterNode
    self.setParameterNode(self.logic.getParameterNode())
  File "C:/Users/26965/AppData/Local/slicer.org/Slicer 5.6.2/3d-slicer/MedSAMSlicer-0.1/MedSAM/MedSAMLite/MedSAMLite.py", line 413, in setParameterNode
    self._parameterNodeGuiTag = self._parameterNode.connectGui(self.ui)
AttributeError: 'MedSAMLiteWidget' object has no attribute 'ui'

**Comment by Franktanshuai** [comment]
i have the same question

**Comment by rasakereh** [comment]
This error per se does not prevent the module from running. do you notice any issues with plugin other than this?
(The latest release)[https://github.com/bowang-lab/MedSAMSlicer/releases/tag/v0.11] has addressed this issue along with a handful of interesting new features
