### ISSUE TITLE
Error running this file infer_video_tiny_debug.py

### ISSUE THREAD

**Issue by lucky-asia** [bowang-lab/MedSAMSlicer#38]
Traceback (most recent call last):
  File "/nfs/gpu_homes/gpu04/home/qiguowei/MedSAMSlicer-SAM2/infer_video_tiny_debug.py", line 297, in <module>
    infer_3d(img_npz_file, gts_file, propagate)
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/nfs/gpu_homes/gpu04/home/qiguowei/MedSAMSlicer-SAM2/infer_video_tiny_debug.py", line 236, in infer_3d
    masks, scores, _ = predictor.predict(point_coords=None, point_labels=None, box=boxes_3D, multimask_output=False,)
  File "/nfs/gpu_homes/gpu04/home/qiguowei/MedSAMSlicer-SAM2/sam2/sam2_image_predictor.py", line 271, in predict
    masks, iou_predictions, low_res_masks = self._predict(
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/nfs/gpu_homes/gpu04/home/qiguowei/MedSAMSlicer-SAM2/sam2/sam2_image_predictor.py", line 400, in _predict
    low_res_masks, iou_predictions, _, _ = self.model.sam_mask_decoder(
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/gpu_homes/gpu04/home/qiguowei/MedSAMSlicer-SAM2/sam2/modeling/sam/mask_decoder.py", line 136, in forward
    masks, iou_pred, mask_tokens_out, object_score_logits = self.predict_masks(
  File "/nfs/gpu_homes/gpu04/home/qiguowei/MedSAMSlicer-SAM2/sam2/modeling/sam/mask_decoder.py", line 213, in predict_masks
    hs, src = self.transformer(src, pos_src, tokens)
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/gpu_homes/gpu04/home/qiguowei/MedSAMSlicer-SAM2/sam2/modeling/sam/transformer.py", line 101, in forward
    queries, keys = layer(
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/gpu_homes/gpu04/home/qiguowei/MedSAMSlicer-SAM2/sam2/modeling/sam/transformer.py", line 167, in forward
    queries = self.self_attn(q=queries, k=queries, v=queries)
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qiguowei/miniconda3/envs/seg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/gpu_homes/gpu04/home/qiguowei/MedSAMSlicer-SAM2/sam2/modeling/sam/transformer.py", line 255, in forward
    out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
RuntimeError: No available kernel. Aborting execution.

**Comment by ivantyj** [comment]
I fix the same problem by refering to https://github.com/facebookresearch/segment-anything-2/issues/48#issuecomment-2266250683,  edit [L22](https://github.com/bowang-lab/MedSAMSlicer/blob/SAM2/sam2/modeling/sam/transformer.py#L22) in `sam2/modeling/sam/transformer.py` to 
```
OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = True, True, True
```
