### ISSUE TITLE
AttributeError: 'MedSAMLiteWidget' object has no attribute 'ui'

### ISSUE THREAD

**Issue by Xavier-1997** [bowang-lab/MedSAMSlicer#50]
I have this problem, please help me. Thanks.

Traceback (most recent call last):
  File "D:/MedSAMSlicer-0.01/MedSAM/MedSAMLite/MedSAMLite.py", line 304, in enter
    self.initializeParameterNode()
  File "D:/MedSAMSlicer-0.01/MedSAM/MedSAMLite/MedSAMLite.py", line 337, in initializeParameterNode
    self.setParameterNode(self.logic.getParameterNode())
  File "D:/MedSAMSlicer-0.01/MedSAM/MedSAMLite/MedSAMLite.py", line 357, in setParameterNode
    self._parameterNodeGuiTag = self._parameterNode.connectGui(self.ui)
AttributeError: 'MedSAMLiteWidget' object has no attribute 'ui'

**Comment by rasakereh** [comment]
Thank you xavier for sharing this. Usually this error doesn't mean anything important. If other functionalities of the plugin hasn't been affected, you can safely ignore this. Otherwise, would you please share more detail on what is not working

**Comment by Xavier-1997** [comment]
Thank you for your reply. I re-installed the relevant packages and the error did not occur again.
