### ISSUE TITLE
GetFullNameFromFileName error

### ISSUE THREAD

**Issue by aclouthier** [bowang-lab/MedSAMSlicer#6]
I get the same error when I try one of the preprocessing options or when I click on Send Image. It's an AttributeError related to GetFullNameFromFileName. The full error message is below.

Traceback (most recent call last):
  File "C:/Users/user/AppData/Local/slicer.org/Slicer 5.6.1/share/Slicer-5.6/Wizard/Templates/Extensions/MedSAMSlicer-0.01/MedSAM/MedSAMLite/MedSAMLite.py", line 241, in <lambda>
    self.ui.pbMRprep.connect('clicked(bool)', lambda: self.logic.applyPreprocess(self.logic.preprocess_MR))
  File "C:/Users/user/AppData/Local/slicer.org/Slicer 5.6.1/share/Slicer-5.6/Wizard/Templates/Extensions/MedSAMSlicer-0.01/MedSAM/MedSAMLite/MedSAMLite.py", line 680, in applyPreprocess
    self.updateImage(method())
  File "C:/Users/user/AppData/Local/slicer.org/Slicer 5.6.1/share/Slicer-5.6/Wizard/Templates/Extensions/MedSAMSlicer-0.01/MedSAM/MedSAMLite/MedSAMLite.py", line 663, in preprocess_MR
    self.captureImage()
  File "C:/Users/user/AppData/Local/slicer.org/Slicer 5.6.1/share/Slicer-5.6/Wizard/Templates/Extensions/MedSAMSlicer-0.01/MedSAM/MedSAMLite/MedSAMLite.py", line 544, in captureImage
    self.img_path = self.volume_node.GetStorageNode().GetFullNameFromFileName()
AttributeError: 'NoneType' object has no attribute 'GetFullNameFromFileName'

**Comment by Enzo-Kerkhof** [comment]
I got the same with the slicer chest CT test data. But it resolved itself after saving the volume on disk to have a normal file path.

**Comment by rasakereh** [comment]
Thanks @Enzo-Kerkhof , yes that is right. For now, we need the file to be saved on the disk to work properly. We will address this matter later to add more flexibility.

**Comment by aclouthier** [comment]
Yes, the image I am using is also stored locally on my computer.

**Comment by huangkai23** [comment]
I get the same error when I click the preprocessing option.

**Comment by vishi334** [comment]
> I got the same with the slicer chest CT test data. But it resolved itself after saving the volume on disk to have a normal file path.

I have saved the volume in .nrrd format and opened the saved volume in slicer. after selecting the ROI, I have clicked on Send Image : I was getting the below error : 

Traceback (most recent call last):
  File "C:\medsam\Slicer 5.4.0\lib\Python\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\medsam\Slicer 5.4.0\lib\Python\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\medsam\Slicer 5.4.0\lib\Python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\medsam\Slicer 5.4.0\lib\Python\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Please explain in detail : how you have saved the file and how you have run it for segmentation.

**Comment by rasakereh** [comment]
Thanks everyone for your feedback. A few hours ago, a new version was released. Would you please upgrade and check if the bug is still there?

**Comment by Enzo-Kerkhof** [comment]
For me the bug is resolved!
